# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vIaZzcxb0T4rVShu6jXGkufUUY8hQaZBqR4K+nK2nvprdYEyBEg/6wpLGw4dua3tezaBWyXGva+++SGdOIjY4NUZxNMna2seZuaQLAoCPrws6Pdg5MGSVOFdw2y1AHcKyc3bpEsdDDT8MxRK0XObzY/PLRLBKl0mr9W0X+vrY7aCO/X11WJld5oRZRMvH88ihCzdRHXGT+pRBtQnRVKXR57J61vJBOxUSg/2agEBDeLG/ZBmwb2Z5SiZuVoZYIPD6ipsMOAN7YO/u2gPW1eL1vohBuG22iDsBA+5I7RYwWlrgsRph9HHePWRaJJfuYynNgdfSLFGA+DmRHXGb6xjMPIP8K504aodSyXUvgrVigrK2jI40Vabd19DkTU3KWuMOqioVBa0cEvHlVfCn3lvm2muZ9b1Hxd0YxJKQHsmS1aNa+lHzj4wjvDVrOnnlxubnac9WVRR00jrt8a5Jb5UyXZDD/1AiaM6cxvT1X9yIe490DRSDtKP7OlW4esKgfnBfdMF6bDBrSRKrfPieg+GkCH2Hlw0v+N92xvyFM44dcS2PO+4XS41m3a9bKxLhlliRPYgh3Nakfs6wAN5KbLnzOKJ7CYNyv2isvkGEG2GhfpcZyF74gFn2vdvDzBR/NbWha2WEQG/dYBa7Bd9SniY7GviHcYJa7dZybabtdyKtgY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
