travis:
  secure:
    BINSTAR_TOKEN: vIaZzcxb0T4rVShu6jXGkufUUY8hQaZBqR4K+nK2nvprdYEyBEg/6wpLGw4dua3tezaBWyXGva+++SGdOIjY4NUZxNMna2seZuaQLAoCPrws6Pdg5MGSVOFdw2y1AHcKyc3bpEsdDDT8MxRK0XObzY/PLRLBKl0mr9W0X+vrY7aCO/X11WJld5oRZRMvH88ihCzdRHXGT+pRBtQnRVKXR57J61vJBOxUSg/2agEBDeLG/ZBmwb2Z5SiZuVoZYIPD6ipsMOAN7YO/u2gPW1eL1vohBuG22iDsBA+5I7RYwWlrgsRph9HHePWRaJJfuYynNgdfSLFGA+DmRHXGb6xjMPIP8K504aodSyXUvgrVigrK2jI40Vabd19DkTU3KWuMOqioVBa0cEvHlVfCn3lvm2muZ9b1Hxd0YxJKQHsmS1aNa+lHzj4wjvDVrOnnlxubnac9WVRR00jrt8a5Jb5UyXZDD/1AiaM6cxvT1X9yIe490DRSDtKP7OlW4esKgfnBfdMF6bDBrSRKrfPieg+GkCH2Hlw0v+N92xvyFM44dcS2PO+4XS41m3a9bKxLhlliRPYgh3Nakfs6wAN5KbLnzOKJ7CYNyv2isvkGEG2GhfpcZyF74gFn2vdvDzBR/NbWha2WEQG/dYBa7Bd9SniY7GviHcYJa7dZybabtdyKtgY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
